# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cTy2MYT3WSRbFciS7EAg12ZypTI2gPg5
"""
import numpy as np
import pickle
# Using flask to make an api 
# import necessary libraries and functions 
from flask import Flask, jsonify, request 

# creating a Flask app 
app = Flask(__name__) 
model = pickle.load(open('final_model_v3.pkl', 'rb'))
# on the terminal type: curl http://127.0.0.1:5000/ 
# returns hello world when we use GET. 
# returns the data that we send when we use POST. 
@app.route('/')
def home(): 
	
		return jsonify({"message" : "Hi! there"}) 

# A simple function to calculate the square of a number 
# the number to be squared is sent in the URL when we use GET 
# on the terminal type: curl http://127.0.0.1:5000 / home / 10 
# this returns 100 (square of 10) 
@app.route('/home/predict', methods = ['POST']) 
def predict(): 
    data = request.get_json(force=True)
    prediction = model.predict([np.array(list(data.values()))])

    output = prediction[0]
    return jsonify(output)


# driver function 
if __name__ == '__main__': 

	app.run(debug = True)
